#!/usr/bin/env bash
case "$BLOCK_BUTTON" in
1) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
esac

MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -o "yes")
VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+(?=%)' | head -1)

if [ "$MUTED" = "yes" ]; then
  echo "♪: muted (${VOL}%) "
else
  echo "♪: ${VOL}% "
fi
