# enable starship
eval "$(starship init zsh)"

# some good stuff
eval "$(zoxide init zsh)"
set -o vi

# aliases
alias l=ls
alias ls="eza --icons=always --color=always"
alias ll="eza -l --icons=always --color=always"
alias la="eza -a --icons=always --color=always"
alias lla="eza -la --icons=always --color=always"
alias tree="eza --tree --icons=always --color=always"
alias cd=z

# a fix for gpg
export GPG_TTY=$(tty)

# env
export EDITOR="nvim"
export TUT_CONF_DIR="$HOME/.config/tut"

# path
export PATH="$PATH:/opt/homebrew/lib/ruby/gems/4.0.0/bin:$HOME/Git/signal-cli/bin:$HOME/.cargo/bin:$HOME/.local/bin"

# startup message
# fastfetch -c neofetch
echo
tmux list-sessions 2>/dev/null
# tmuxinator list 2>/dev/null

# secrets
[ -f ~/.secrets ] && source ~/.secrets
